/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCombination: typeof import('./src/components/Script/ActionCombination.vue')['default']
    AddModuleDrawer: typeof import('./src/components/Requirement/AddModuleDrawer.vue')['default']
    AddProject: typeof import('./src/components/Project/AddProject.vue')['default']
    AddRequirementDocx: typeof import('./src/components/Requirement/AddRequirementDocx.vue')['default']
    copy: typeof import('./src/components/Requirement/TestCaseInner copy.vue')['default']
    DocumentWordEditor: typeof import('./src/components/Requirement/DocumentWordEditor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Empty: typeof import('./src/components/Empty.vue')['default']
    FillModal: typeof import('./src/components/UseCase/FillModal.vue')['default']
    FunctionModule: typeof import('./src/components/Requirement/FunctionModule.vue')['default']
    FunctionPoint: typeof import('./src/components/Requirement/FunctionPoint.vue')['default']
    HistoryVersionModal: typeof import('./src/components/Requirement/HistoryVersionModal.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu/LeftMenu.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    MetaAction: typeof import('./src/components/Script/MetaAction.vue')['default']
    ProjectDetail: typeof import('./src/components/Project/ProjectDetail.vue')['default']
    ProjectManage: typeof import('./src/components/Project/ProjectManage.vue')['default']
    Registry: typeof import('./src/components/Registry.vue')['default']
    RequirementDocx: typeof import('./src/components/Requirement/RequirementDocx.vue')['default']
    RequirementInner: typeof import('./src/components/Requirement/RequirementInner.vue')['default']
    RequirementMain: typeof import('./src/components/Requirement/RequirementMain.vue')['default']
    RequirementManage: typeof import('./src/components/Requirement/RequirementManage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScriptFile: typeof import('./src/components/Script/ScriptFile.vue')['default']
    SplitCaseInner: typeof import('./src/components/Requirement/SplitCaseInner.vue')['default']
    SplitRequirementInner: typeof import('./src/components/Requirement/SplitRequirementInner.vue')['default']
    TestCaseInner: typeof import('./src/components/Requirement/TestCaseInner.vue')['default']
    TestCaseInnerNew: typeof import('./src/components/Requirement/TestCaseInnerNew.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UseCase: typeof import('./src/components/UseCase/UseCase.vue')['default']
  }
}

// For TSX support
declare global {
  const ActionCombination: typeof import('./src/components/Script/ActionCombination.vue')['default']
  const AddModuleDrawer: typeof import('./src/components/Requirement/AddModuleDrawer.vue')['default']
  const AddProject: typeof import('./src/components/Project/AddProject.vue')['default']
  const AddRequirementDocx: typeof import('./src/components/Requirement/AddRequirementDocx.vue')['default']
  const copy: typeof import('./src/components/Requirement/TestCaseInner copy.vue')['default']
  const DocumentWordEditor: typeof import('./src/components/Requirement/DocumentWordEditor.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElTable: typeof import('element-plus/es')['ElTable']
  const ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
  const Empty: typeof import('./src/components/Empty.vue')['default']
  const FillModal: typeof import('./src/components/UseCase/FillModal.vue')['default']
  const FunctionModule: typeof import('./src/components/Requirement/FunctionModule.vue')['default']
  const FunctionPoint: typeof import('./src/components/Requirement/FunctionPoint.vue')['default']
  const HistoryVersionModal: typeof import('./src/components/Requirement/HistoryVersionModal.vue')['default']
  const LeftMenu: typeof import('./src/components/LeftMenu/LeftMenu.vue')['default']
  const Login: typeof import('./src/components/Login.vue')['default']
  const MetaAction: typeof import('./src/components/Script/MetaAction.vue')['default']
  const ProjectDetail: typeof import('./src/components/Project/ProjectDetail.vue')['default']
  const ProjectManage: typeof import('./src/components/Project/ProjectManage.vue')['default']
  const Registry: typeof import('./src/components/Registry.vue')['default']
  const RequirementDocx: typeof import('./src/components/Requirement/RequirementDocx.vue')['default']
  const RequirementInner: typeof import('./src/components/Requirement/RequirementInner.vue')['default']
  const RequirementMain: typeof import('./src/components/Requirement/RequirementMain.vue')['default']
  const RequirementManage: typeof import('./src/components/Requirement/RequirementManage.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ScriptFile: typeof import('./src/components/Script/ScriptFile.vue')['default']
  const SplitCaseInner: typeof import('./src/components/Requirement/SplitCaseInner.vue')['default']
  const SplitRequirementInner: typeof import('./src/components/Requirement/SplitRequirementInner.vue')['default']
  const TestCaseInner: typeof import('./src/components/Requirement/TestCaseInner.vue')['default']
  const TestCaseInnerNew: typeof import('./src/components/Requirement/TestCaseInnerNew.vue')['default']
  const TopBar: typeof import('./src/components/TopBar.vue')['default']
  const UseCase: typeof import('./src/components/UseCase/UseCase.vue')['default']
}