server {
  listen 80;
  server_name _;

  # 静态文件路径
  root /usr/share/nginx/html;
  index index.html;

  # 代理 /dev-api 接口，并添加 CORS 头
  # location /dev-api/ {
  #   proxy_pass http://183.66.251.10:57000/;
  #   proxy_set_header Host $host;
  #   proxy_set_header X-Real-IP $remote_addr;
  #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  #   proxy_set_header X-Forwarded-Proto $scheme;

  #   # CORS 跨域头
  #   add_header Access-Control-Allow-Origin * always;
  #   add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
  #   add_header Access-Control-Allow-Headers 'Content-Type, Authorization' always;

  #   # 响应时间改为5分钟
  #   proxy_read_timeout 300s;
  #   proxy_send_timeout 300s;
  #   proxy_connect_timeout 300s;
  #   send_timeout 300s;
    
  #   # 预检请求快速返回
  #   if ($request_method = OPTIONS) {
  #     return 204;
  #   }
  # }

  # 支持 SPA history 模式
  location / {
    try_files $uri $uri/ /index.html;
  }
}